name: Android Release CI

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  release:
    name: Build & Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Create keystore.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
          echo "storeFile=keystore.jks" >> keystore.properties

      - name: Read latest version tag
        id: version
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          VERSION=${TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          if [ "${{ github.event.inputs.bump }}" = "major" ]; then
            MAJOR=$((MAJOR+1)); MINOR=0; PATCH=0
          elif [ "${{ github.event.inputs.bump }}" = "minor" ]; then
            MINOR=$((MINOR+1)); PATCH=0
          else
            PATCH=$((PATCH+1))
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          NEW_CODE=$(git rev-list --count HEAD)

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "new_code=$NEW_CODE" >> $GITHUB_OUTPUT

      - name: Grant Gradle permission
        run: chmod +x gradlew

      - name: Build Release APK
        env:
          VERSION_NAME: ${{ steps.version.outputs.new_version }}
          VERSION_CODE: ${{ steps.version.outputs.new_code }}
        run: ./gradlew assembleRelease
        
      - name: Rename APK with version
        run: |
          mv app/build/outputs/apk/release/app-release.apk  app/build/outputs/apk/release/shopping-list-app-v${{ steps.version.outputs.new_version }}(${{ steps.version.outputs.new_code }})-release.apk
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.new_version }}
          name: Android Release v${{ steps.version.outputs.new_version }}
          files: app/build/outputs/apk/release/shopping-list-app-v${{ steps.version.outputs.new_version }}(${{ steps.version.outputs.new_code }})-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
